name: Deploying AWS Lambda Functions

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'modelling/hyperparam_search/**'
      - '.github/workflows/deploy_lambdas.yml'

permissions:
  id-token: write   # This is required for OIDC authentication
  contents: read    # This is required to checkout the repository

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}
        # The role-to-assume should be the ARN of the IAM role you created for GitHub Actions OIDC

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r modelling/hyperparam_search/requirements.txt -t modelling/hyperparam_search/

    - name: Deploy Lambda Function
      uses: aws-actions/aws-lambda-deploy@v1.1.0
      with:
        function-name: hdb-resale-hyperparam-search # Have to create this lambda function on AWS already.
        code-artifacts-dir: modelling/hyperparam_search
        handler: hyperparam_search.lambda_handler
        runtime: python3.12
        # Add any additional inputs this action supports