name: Deploying AWS Lambda Functions

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'modelling/data_processing/**'
      - '.github/workflows/deploy_lambdas.yml'

permissions:
  id-token: write   # This is required for OIDC authentication
  contents: read    # This is required to checkout the repository

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}
        # The role-to-assume should be the ARN of the IAM role you created for GitHub Actions OIDC
        # The role should have a trust relationship with the GitHub OIDC provider
    - name: Update hdb-resale-process-data Lambda function
      uses: aws-actions/aws-lambda-deploy@v1.1.0
      with:
        function-name: hdb-resale-process-data
        code-artifacts-dir: modelling/data_processing

