name: Deploying AWS Lambda Functions

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'modelling/hyperparam_search/**'
      - '.github/workflows/deploy_lambdas.yml'

permissions:
  id-token: write   # This is required for OIDC authentication
  contents: read    # This is required to checkout the repository

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}
        # The role-to-assume should be the ARN of the IAM role you created for GitHub Actions OIDC

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      # Authenticates with ECR and returns the registry URL for building images

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: zy/hdb-hyperparam-search
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build Docker image from Dockerfile in repository root
        docker build -f modelling/hyperparam_search/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        # Push the built image to ECR repository
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        # Output the full image URI for the next step
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Deploy Lambda function with container image
      uses: aws-actions/aws-lambda-deploy@v1.1.0
      with:
        function-name: hdb-resale-hyperparam-search  # Name of the Lambda function to deploy
        package-type: Image  # Required: Indicates container deployment (not zip)
        image-uri: ${{ steps.build-image.outputs.image }}  # ECR image URI from previous step
        role: ${{ secrets.AWS_OIDC_ROLE }}  # IAM execution role for Lambda
        # Note: handler, runtime, and layers should not be provided for container images
