name: Continuous Integration & Deployment
on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]
  
permissions: write-all
jobs:
  train_model:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read  # Required to check out the repository
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GitHubActionRole
          aws-region: ap-southeast-1
      
      - name: Deploy Lambda Function
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: hdb-resale-data-s3
          code-artifacts-dir: ./dist
